# Campus Service - Unified Deployment
# This configuration supports both vault and apps deployments
# Deployment mode determined by 'deploy' file content

[tool.poetry]
name = "campus-vault"
version = "0.1.0"
description = "Vault - Secrets management service for Campus"
authors = ["Ng Jun Siang <ngjunsiang@gmail.com>"]
readme = "README.md"
packages = [{include = "campus"}]

[tool.poetry.dependencies]
python = ">=3.11.0,<3.12"

# All dependencies bundled for simplicity
flask = "^3.0.0"
bcrypt = "^4.2.1"
psycopg2-binary = "^2.9.0"
pymongo = {extras = ["srv"], version = "^4.8.0"}
requests = "^2.32.4"
gunicorn = "^21.2.0"
werkzeug = "^3.0.0"

[tool.poetry.group.dev.dependencies]
pylint = "^3.0"

[tool.poetry.scripts]
campus = "main:main"

[tool.pyright]
useLibraryCodeForTypes = true
exclude = [".cache"]

[tool.ruff]
select = ['E', 'W', 'F', 'I', 'B', 'C4', 'ARG', 'SIM']
ignore = ['W291', 'W292', 'W293']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
