# Campus - Deployment Orchestrator & Client Library
# This configuration supports deployment orchestration and client library distribution
# Deployment mode determined by 'deploy' file content

[tool.poetry]
name = "campus"
version = "0.1.0"
description = "Campus deployment orchestrator and client library for vault and apps services"
authors = ["Ng Jun Siang <ngjunsiang@gmail.com>"]
readme = "README.md"
packages = [{include = "campus"}]

[tool.poetry.dependencies]
python = ">=3.11.0,<3.12"

# Client library dependencies (minimal for HTTP requests)
requests = "^2.32.4"

# Deployment orchestration dependencies (all services)
flask = {version = "^3.0.0", optional = true}
bcrypt = {version = "^4.2.1", optional = true}
psycopg2-binary = {version = "^2.9.0", optional = true}
pymongo = {extras = ["srv"], version = "^4.13.2", optional = true}
gunicorn = {version = "^21.2.0", optional = true}
werkzeug = {version = "^3.0.0", optional = true}

[tool.poetry.extras]
# Optional dependency groups for deployment modes
vault = ["flask", "bcrypt", "psycopg2-binary", "gunicorn", "werkzeug"]
apps = ["flask", "bcrypt", "psycopg2-binary", "pymongo", "gunicorn", "werkzeug"]
full = ["flask", "bcrypt", "psycopg2-binary", "pymongo", "gunicorn", "werkzeug"]

[tool.poetry.group.dev.dependencies]
pylint = "^3.0"

[tool.poetry.scripts]
campus = "main:main"

[tool.pyright]
useLibraryCodeForTypes = true
exclude = [".cache"]

[tool.ruff]
select = ['E', 'W', 'F', 'I', 'B', 'C4', 'ARG', 'SIM']
ignore = ['W291', 'W292', 'W293']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
