[tool.poetry]
name = "campus-workspace"
version = "0.1.0"
description = "Campus ecosystem workspace - contains all Campus packages"
authors = ["Ng Jun Siang <ngjunsiang@gmail.com>"]
package-mode = false

# Workspace configuration - install all packages in development mode
[tool.poetry.dependencies]
python = ">=3.11.0,<3.12"
# Local packages installed in development mode
campus-common = {path = "./campus/common", develop = true}
campus-vault = {path = "./campus/vault", develop = true}
campus-storage = {path = "./campus/storage", develop = true}
campus-client = {path = "./campus/client", develop = true}
campus-models = {path = "./campus/models", develop = true}
campus-apps = {path = "./campus/apps", develop = true}

[tool.poetry.group.dev.dependencies]
pylint = "^3.0"

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
useLibraryCodeForTypes = true
exclude = [".cache"]

[tool.ruff]
# https://beta.ruff.rs/docs/configuration/
select = ['E', 'W', 'F', 'I', 'B', 'C4', 'ARG', 'SIM']
ignore = ['W291', 'W292', 'W293']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"