"""campus.auth.resources.client

Client resource for Campus API.
"""

__all__ = []

import logging
import typing

import campus.config
import campus.model as model
import campus.storage
from campus.common import env, schema
from campus.common.errors import api_errors, auth_errors
from campus.common.utils import secret

from . import grant as grant_resource

client_storage = campus.storage.get_table("vault_clients")

logger = logging.getLogger(__name__)

# Idempotent schema alignment for client schema changes that postdate
# a deployment's vault_clients table. Matches the columns generated by
# _model_to_sql_schema(model.Client), with DEFAULT clauses so the NOT
# NULL columns backfill existing rows.
# Mirrors migrations/004_add_vault_clients_public_columns.py and
# migrations/006_add_client_allowed_scopes.py.
_CLIENT_SCHEMA_SQL = """
ALTER TABLE "vault_clients" ADD COLUMN IF NOT EXISTS "is_public" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "vault_clients" ADD COLUMN IF NOT EXISTS "redirect_uris" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "vault_clients" ADD COLUMN IF NOT EXISTS "allowed_scopes" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "vault_clients" ADD COLUMN IF NOT EXISTS "upstream_scopes" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "vault_clients" ADD COLUMN IF NOT EXISTS "token_bridge" BOOLEAN NOT NULL DEFAULT FALSE;
"""


def ensure_public_client_schema() -> None:
    """Align the vault_clients table schema with the current client model.

    Adds the is_public and redirect_uris columns if the table predates
    PR #604, allowed_scopes if it predates the scope-allowlist work
    (#705), upstream_scopes if it predates the upstream-scope work,
    and token_bridge if it predates the token-bridge work.
    CREATE TABLE IF NOT EXISTS (init_storage) never alters an
    existing table, so databases initialized before those changes
    lack the columns: reads tolerate their absence, but inserting a
    client fails with UndefinedColumn (observed on the development
    deployment, #605).

    Idempotent: safe to run on every startup.

    No-op in test mode (test databases are created fresh from the
    model, and SQLite does not support ADD COLUMN IF NOT EXISTS) and
    in production (schema changes go through migrations; apply
    migrations/004, 006, 007 and 008).
    """
    from campus.common import env
    from campus.storage.testing import is_test_mode

    if is_test_mode():
        return

    if env.ENV == env.PRODUCTION:
        return

    client_storage.init_from_schema(_CLIENT_SCHEMA_SQL)


def _get_client_permissions(
        client_id: schema.CampusID | str
) -> dict[str, int]:
    """Get a client's vault access permissions.

    Args:
        client_id: The client identifier

    Returns:
        Dictionary mapping vault labels to permission bitflags
    """
    access_records = grant_resource.grant_storage.get_matching({
        "grantee_type": "client",
        "grantee_id": client_id,
        "resource_type": "vault",
    })
    permissions: dict[str, int] = {}
    for record in access_records:
        label = schema.String(record["resource_id"])
        access_flag = schema.Integer(record["bits"])
        permissions[label] = access_flag
    return permissions


def _get_all_client_permissions() -> dict[str, dict[str, int]]:
    """Get all clients' vault access permissions.

    Args:
        None

    Returns:
        Dictionary mapping vault labels to permission bitflags
    """
    access_records = grant_resource.grant_storage.get_matching({
        "grantee_type": "client",
        "resource_type": "vault",
    })
    permissions: dict[str, dict[str, int]] = {}
    for record in access_records:
        label = schema.String(record["resource_id"])
        access_flag = schema.Integer(record["bits"])
        client_id = record["grantee_id"]
        if client_id not in permissions:
            permissions[client_id] = {}
        permissions[client_id][label] = access_flag
    return permissions


def ensure_public_client() -> bool:
    """Ensure the public OAuth client for CLI/device apps exists.

    Creates the public client identified by
    campus.config.PUBLIC_OAUTH_CLIENT_ID if it is missing from storage.
    This is the client used for the OAuth 2.0 Device Authorization Flow
    (RFC 8628) by CLI, mobile and native applications that cannot
    securely store client credentials (RFC 6749 Section 2.1 public
    clients). It has no secret and is validated by client_id only.

    This seed cannot go through the HTTP API: creating a client requires
    an authenticated token, which requires completing the device flow,
    which requires this client to exist (chicken-and-egg). It must be
    applied directly against storage.

    Idempotent: safe to re-run on every startup and deployment. An
    existing record is never modified.

    Returns:
        True if the client was created, False if it already existed.

    Raises:
        campus.storage.errors.StorageError: If the client record cannot
            be read or created.
    """
    client_id = schema.CampusID(campus.config.PUBLIC_OAUTH_CLIENT_ID)
    try:
        client_storage.get_by_id(client_id)
        return False
    except campus.storage.errors.NotFoundError:
        pass

    client = model.Client(
        id=client_id,
        name="Public CLI Client",
        description="Public OAuth client for CLI and device applications",
        is_public=True,
        # RFC 8628 out-of-band redirect URI for device flow clients
        redirect_uris=["urn:ietf:wg:oauth:2.0:oob"],
        # Fail-closed scope allowlist (invariant A1): the seeded CLI
        # client may hold exactly the default device-flow scopes.
        allowed_scopes=list(campus.config.DEFAULT_CLI_SCOPES),
    )
    try:
        client_storage.insert_one(client.to_storage())
    except campus.storage.ConflictError:
        # Either a concurrent worker seeded this client first, or the
        # UNIQUE name is held by a different client.
        try:
            client_storage.get_by_id(client_id)
            return False  # Concurrently seeded; desired end state reached
        except campus.storage.errors.NotFoundError:
            logger.error(
                "Cannot seed public OAuth client '%s': another client "
                "already holds the name '%s'. Rename or remove that "
                "client, then restart the service to retry the seed.",
                client_id,
                client.name
            )
            return False
    return True


class ClientsResource:
    """Represents the clients resource in Campus API Schema."""

    @staticmethod
    def init_storage() -> None:
        """Initialize storage for client authentication."""
        client_storage.init_from_model("vault_clients", model.Client)
        grant_resource.grants.init_storage()

    def __getitem__(
            self,
            client_id: schema.CampusID | str
    ) -> "ClientResource":
        """Get a client resource by client ID.

        Args:
            client_id: The vault client ID

        Returns:
            ClientResource instance
        """
        return ClientResource(schema.CampusID(client_id))

    def is_valid_credentials(
            self,
            client_id: schema.CampusID | str,
            client_secret: str | None = None
    ) -> bool:
        """Check if client credentials are valid.

        Args:
            client_id: The client identifier
            client_secret: The client secret (optional for public clients)
        Returns:
            True if credentials are valid, False otherwise
        """
        client = self[schema.CampusID(client_id)].get()

        # Public clients (CLI, mobile) are validated by client_id only
        if client.is_public:
            if client_secret is not None:
                raise auth_errors.UnauthorizedClientError(
                    "Public client should not provide a secret",
                    client_id=client_id
                )
            return True

        # Confidential clients must have a valid secret
        if not client.secret_hash:
            raise auth_errors.ServerError(
                "Invalid configuration - confidential client missing secret_hash",
                client_id=client_id
            )
        if client_secret is None:
            raise auth_errors.UnauthorizedClientError(
                "Confidential client requires a secret",
                client_id=client_id
            )
        expected_hash = secret.hash_client_secret(
            client_secret,
            env.getsecret("SECRET_KEY")
        )
        return client.secret_hash == expected_hash

    def raise_for_authentication(
            self,
            client_id: schema.CampusID | str,
            client_secret: str
    ) -> None:
        """Authenticate a client using their ID and secret.
        Pushes the authenticated client into flask.g.current_client if
        successful, otherwise raises an authentication error.

        Args:
            client_id: The client identifier
            client_secret: The client secret

        Raises:
            UnauthorizedError: If client not found or client secret is invalid
        """
        client_id = schema.CampusID(client_id)
        if not self.is_valid_credentials(client_id, client_secret):
            raise auth_errors.UnauthorizedClientError(
                "Invalid credentials",
                client_id=client_id
            )

    def list_all(self) -> list[model.Client]:
        """List all clients.

        Returns:
            List of Client instances
        """
        records = client_storage.get_matching({})
        access = _get_all_client_permissions()
        clients = []
        for record in records:
            client = model.Client.from_storage(record)
            client.permissions = access.get(client.id, {})
            clients.append(client)
        return clients

    def new(
            self,
            **kwargs: typing.Any
    ) -> model.Client:
        """Create a new client and return it.

        Args:
            **kwargs: Additional fields for client creation

        Returns:
            Client instance

        Raises:
            api_errors.ConflictError: If a client with the same name
                already exists (vault_clients.name is UNIQUE).
        """
        client = model.Client(**kwargs)
        try:
            client_storage.insert_one(client.to_storage())
        except campus.storage.errors.ConflictError as e:
            raise api_errors.ConflictError(
                message=f"Client name '{client.name}' already exists",
                name=client.name
            ) from e
        return client


class ClientResource:
    """Represents a single client in Campus API Schema."""

    def __init__(self, client_id: schema.CampusID | str):
        self.client_id = schema.CampusID(client_id)

    @property
    def access(self) -> "ClientAccessResource":
        """Get the client access resource.

        Returns:
            ClientAccessResource instance
        """
        return ClientAccessResource(self)

    def delete(self) -> None:
        """Delete the client record."""
        client_storage.delete_by_id(self.client_id)

    def get(self) -> model.Client:
        """Get the client record.

        Returns:
            ClientRecord instance
        """
        client_id = self.client_id
        try:
            record = client_storage.get_by_id(client_id)
        except campus.storage.errors.NotFoundError:
            raise auth_errors.InvalidRequestError(
                f"Client '{client_id}' not found",
                client_id=client_id
            ) from None
        client = model.Client.from_storage(record)
        # Permissions live in a separate collection; join after the
        # storage-shape mapping.
        client.permissions = _get_client_permissions(client_id)
        return client

    def revoke(self) -> str:
        """Revoke the client by deleting its secret.

        Returns:
            The generated client secret

        Raises:
            auth_errors.InvalidRequestError: If client is public (no secret to revoke)
        """
        # Check if client exists first
        client = self.get()
        if client.is_public:
            raise auth_errors.InvalidRequestError(
                "Public clients do not have a secret to revoke",
                client_id=self.client_id
            )
        new_secret = secret.generate_client_secret()
        secret_hash = secret.hash_client_secret(
            secret=new_secret,
            key=env.getsecret("SECRET_KEY")
        )
        client_storage.update_by_id(
            self.client_id,
            {"secret_hash": secret_hash}
        )
        return new_secret

    def update(self, **updates: typing.Any) -> None:
        """Update the client record.

        Args:
            **updates: Fields to update (name, description)

        Raises:
            api_errors.ConflictError: If renaming the client to a name
                that already exists (vault_clients.name is UNIQUE).
        """
        model.Client.validate_update(updates)
        try:
            client_storage.update_by_id(self.client_id, updates)
        except campus.storage.errors.ConflictError as e:
            raise api_errors.ConflictError(
                message=f"Client name '{updates.get('name')}' already exists",
                name=updates.get("name")
            ) from e


class ClientAccessResource:
    """Vault-access view over the access-grant store (#884).

    Preserves the pre-#884 public surface and semantics of the
    vault_access table, now as (client grantee, vault resource) grant
    rows administered by the same /clients/{id}/access/ routes. The
    generalized GrantsResource (campus.auth.resources.grant) is the
    full store; this class is the vault compatibility layer.
    """

    def __init__(self, parent: "ClientResource"):
        self._parent = parent

    def check(
            self,
            vault_label: str,
            permission: int
    ) -> bool:
        """Check if client has required permission for vault label.

        Args:
            vault_label: The vault label to check access for
            permission: The permission bitflag required (READ, CREATE,
            UPDATE, DELETE)

        Returns:
            True if any requested bit is held on the label
        """
        return grant_resource.grants.check(
            "client", self._parent.client_id, "vault", vault_label,
            bits=permission,
        )

    def get(
            self,
            vault_label: str
    ) -> int:
        """Get the client's permission bitflag for a vault label.

        Args:
            vault_label: The vault label to get access for

        Returns:
            The permission bitflag for the vault label
        """
        row = grant_resource.grants.get(
            "client", self._parent.client_id, "vault", vault_label
        )
        return int(row["bits"]) if row else 0

    def grant(
            self,
            vault_label: str,
            permission: int
    ) -> None:
        """Grant the client access permission for a vault label.

        Args:
            vault_label: The vault label to grant access for
            permission: The permission bitflag to grant (OR-ed into
            any existing mask)
        """
        grant_resource.grants.grant(
            "client", self._parent.client_id, "vault", vault_label,
            bits=permission,
        )

    def list(self) -> dict[str, int]:
        """List all vault access permissions for the client.

        Returns:
            Dictionary mapping vault labels to permission bitflags
        """
        rows = grant_resource.grants.list(
            grantee_type="client",
            grantee_id=self._parent.client_id,
            resource_type="vault",
        )
        return {row["resource_id"]: int(row["bits"]) for row in rows}

    def revoke(
            self,
            vault_label: str,
            permission: int
    ) -> None:
        """Revoke the client access permission for a vault label.

        Args:
            vault_label: The vault label to revoke access for
            permission: The permission bitflag to revoke (the grant
            row is deleted when no bits remain)
        """
        grant_resource.grants.revoke(
            "client", self._parent.client_id, "vault", vault_label,
            bits=permission,
        )

    def update(
            self,
            vault_label: str,
            permission: int
    ) -> None:
        """Update (replace) the client access permission for a vault label.

        Args:
            vault_label: The vault label to update access for
            permission: The permission bitflag to set (replaces the
            existing mask; zero deletes the grant)
        """
        grant_resource.grants.update(
            "client", self._parent.client_id, "vault", vault_label,
            bits=permission,
        )
