"""campus.auth.resources.client

Client resource for Campus API.
"""

__all__ = []

import typing

import logging

import campus.config
from campus.common import env, schema
from campus.common.errors import api_errors, auth_errors
from campus.common.utils import secret, uid
import campus.model as model
import campus.storage

client_storage = campus.storage.get_table("vault_clients")
access_storage = campus.storage.get_table("vault_access")

logger = logging.getLogger(__name__)

# Idempotent schema alignment for public client support (PR #604).
# Matches the columns generated by _model_to_sql_schema(model.Client),
# with DEFAULT clauses so the NOT NULL columns backfill existing rows.
# Mirrors migrations/004_add_vault_clients_public_columns.py.
_PUBLIC_CLIENT_SCHEMA_SQL = """
ALTER TABLE "vault_clients" ADD COLUMN IF NOT EXISTS "is_public" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "vault_clients" ADD COLUMN IF NOT EXISTS "redirect_uris" TEXT NOT NULL DEFAULT '[]';
"""


def ensure_public_client_schema() -> None:
    """Align the vault_clients table schema for public client support.

    Adds the is_public and redirect_uris columns if the table predates
    PR #604. CREATE TABLE IF NOT EXISTS (init_storage) never alters an
    existing table, so databases initialized before that change lack
    the columns: reads tolerate their absence, but inserting the public
    client fails with UndefinedColumn (observed on the development
    deployment, #605).

    Idempotent: safe to run on every startup.

    No-op in test mode (test databases are created fresh from the
    model, and SQLite does not support ADD COLUMN IF NOT EXISTS) and
    in production (schema changes go through migrations; apply
    migrations/004_add_vault_clients_public_columns.py).
    """
    from campus.common import devops
    from campus.storage.testing import is_test_mode

    if is_test_mode():
        return

    if devops.ENV == devops.PRODUCTION:
        return

    client_storage.init_from_schema(_PUBLIC_CLIENT_SCHEMA_SQL)


def _from_record(
        record: dict[str, typing.Any],
        permissions: dict[str, int] | None = None
) -> model.Client:
    """Convert a storage record to a Client model instance."""
    return model.Client(
        id=schema.CampusID(record["id"]),
        created_at=schema.DateTime(
            record.get("created_at", schema.DateTime.utcnow())
        ),
        name=record["name"],
        description=record["description"],
        is_public=record.get("is_public", False),
        redirect_uris=record.get("redirect_uris", []),
        permissions=permissions or {},
        secret_hash=record.get("secret_hash"),
    )


def _get_client_permissions(
        client_id: schema.CampusID | str
) -> dict[str, int]:
    """Get a client's vault access permissions.

    Args:
        client_id: The client identifier

    Returns:
        Dictionary mapping vault labels to permission bitflags
    """
    access_records = access_storage.get_matching({"client_id": client_id})
    permissions: dict[str, int] = {}
    for record in access_records:
        label = schema.String(record["label"])
        access_flag = schema.Integer(record["access"])
        permissions[label] = access_flag
    return permissions


def _get_all_client_permissions() -> dict[str, dict[str, int]]:
    """Get all clients' vault access permissions.

    Args:
        None

    Returns:
        Dictionary mapping vault labels to permission bitflags
    """
    access_records = access_storage.get_matching({})
    permissions: dict[str, dict[str, int]] = {}
    for record in access_records:
        label = schema.String(record["label"])
        access_flag = schema.Integer(record["access"])
        client_id = record["client_id"]
        if client_id not in permissions:
            permissions[client_id] = {}
        permissions[client_id][label] = access_flag
    return permissions


def ensure_public_client() -> bool:
    """Ensure the public OAuth client for CLI/device apps exists.

    Creates the public client identified by
    campus.config.PUBLIC_OAUTH_CLIENT_ID if it is missing from storage.
    This is the client used for the OAuth 2.0 Device Authorization Flow
    (RFC 8628) by CLI, mobile and native applications that cannot
    securely store client credentials (RFC 6749 Section 2.1 public
    clients). It has no secret and is validated by client_id only.

    This seed cannot go through the HTTP API: creating a client requires
    an authenticated token, which requires completing the device flow,
    which requires this client to exist (chicken-and-egg). It must be
    applied directly against storage.

    Idempotent: safe to re-run on every startup and deployment. An
    existing record is never modified.

    Returns:
        True if the client was created, False if it already existed.

    Raises:
        campus.storage.errors.StorageError: If the client record cannot
            be read or created.
    """
    client_id = schema.CampusID(campus.config.PUBLIC_OAUTH_CLIENT_ID)
    try:
        client_storage.get_by_id(client_id)
        return False
    except campus.storage.errors.NotFoundError:
        pass

    client = model.Client(
        id=client_id,
        name="Public CLI Client",
        description="Public OAuth client for CLI and device applications",
        is_public=True,
        # RFC 8628 out-of-band redirect URI for device flow clients
        redirect_uris=["urn:ietf:wg:oauth:2.0:oob"],
    )
    try:
        client_storage.insert_one(client.to_storage())
    except campus.storage.ConflictError:
        # Either a concurrent worker seeded this client first, or the
        # UNIQUE name is held by a different client.
        try:
            client_storage.get_by_id(client_id)
            return False  # Concurrently seeded; desired end state reached
        except campus.storage.errors.NotFoundError:
            logger.error(
                "Cannot seed public OAuth client '%s': another client "
                "already holds the name '%s'. Rename or remove that "
                "client, then restart the service to retry the seed.",
                client_id,
                client.name
            )
            return False
    return True


class ClientsResource:
    """Represents the clients resource in Campus API Schema."""

    @staticmethod
    def init_storage() -> None:
        """Initialize storage for client authentication."""
        client_storage.init_from_model("vault_clients", model.Client)
        access_storage.init_from_model(
            "vault_access", model.ClientAccess
        )

    def __getitem__(
            self,
            client_id: schema.CampusID | str
    ) -> "ClientResource":
        """Get a client resource by client ID.

        Args:
            client_id: The vault client ID

        Returns:
            ClientResource instance
        """
        return ClientResource(schema.CampusID(client_id))

    def is_valid_credentials(
            self,
            client_id: schema.CampusID | str,
            client_secret: str | None = None
    ) -> bool:
        """Check if client credentials are valid.

        Args:
            client_id: The client identifier
            client_secret: The client secret (optional for public clients)
        Returns:
            True if credentials are valid, False otherwise
        """
        client = self[schema.CampusID(client_id)].get()

        # Public clients (CLI, mobile) are validated by client_id only
        if client.is_public:
            if client_secret is not None:
                raise auth_errors.UnauthorizedClientError(
                    "Public client should not provide a secret",
                    client_id=client_id
                )
            return True

        # Confidential clients must have a valid secret
        if not client.secret_hash:
            raise auth_errors.ServerError(
                "Invalid configuration - confidential client missing secret_hash",
                client_id=client_id
            )
        if client_secret is None:
            raise auth_errors.UnauthorizedClientError(
                "Confidential client requires a secret",
                client_id=client_id
            )
        expected_hash = secret.hash_client_secret(
            client_secret,
            env.getsecret("SECRET_KEY")
        )
        return client.secret_hash == expected_hash

    def raise_for_authentication(
            self,
            client_id: schema.CampusID | str,
            client_secret: str
    ) -> None:
        """Authenticate a client using their ID and secret.
        Pushes the authenticated client into flask.g.current_client if
        successful, otherwise raises an authentication error.

        Args:
            client_id: The client identifier
            client_secret: The client secret

        Raises:
            UnauthorizedError: If client not found or client secret is invalid
        """
        client_id = schema.CampusID(client_id)
        if not self.is_valid_credentials(client_id, client_secret):
            raise auth_errors.UnauthorizedClientError(
                "Invalid credentials",
                client_id=client_id
            )

    def list_all(self) -> list[model.Client]:
        """List all clients.

        Returns:
            List of Client instances
        """
        records = client_storage.get_matching({})
        access = _get_all_client_permissions()
        clients = []
        for record in records:
            client = model.Client.from_storage(record)
            client.permissions = access.get(client.id, {})
            clients.append(client)
        return clients

    def new(
            self,
            **kwargs: typing.Any
    ) -> model.Client:
        """Create a new client and return it.

        Args:
            **kwargs: Additional fields for client creation

        Returns:
            Client instance

        Raises:
            api_errors.ConflictError: If a client with the same name
                already exists (vault_clients.name is UNIQUE).
        """
        client = model.Client(**kwargs)
        try:
            client_storage.insert_one(client.to_storage())
        except campus.storage.errors.ConflictError as e:
            raise api_errors.ConflictError(
                message=f"Client name '{client.name}' already exists",
                name=client.name
            ) from e
        return client


class ClientResource:
    """Represents a single client in Campus API Schema."""

    def __init__(self, client_id: schema.CampusID | str):
        self.client_id = schema.CampusID(client_id)

    @property
    def access(self) -> "ClientAccessResource":
        """Get the client access resource.

        Returns:
            ClientAccessResource instance
        """
        return ClientAccessResource(self)

    def delete(self) -> None:
        """Delete the client record."""
        client_storage.delete_by_id(self.client_id)

    def get(self) -> model.Client:
        """Get the client record.

        Returns:
            ClientRecord instance
        """
        client_id = self.client_id
        try:
            record = client_storage.get_by_id(client_id)
        except campus.storage.errors.NotFoundError:
            raise auth_errors.InvalidRequestError(
                f"Client '{client_id}' not found",
                client_id=client_id
            )
        return _from_record(
            record=record,
            permissions=_get_client_permissions(client_id)
        )

    def revoke(self) -> str:
        """Revoke the client by deleting its secret.

        Returns:
            The generated client secret

        Raises:
            auth_errors.InvalidRequestError: If client is public (no secret to revoke)
        """
        # Check if client exists first
        client = self.get()
        if client.is_public:
            raise auth_errors.InvalidRequestError(
                "Public clients do not have a secret to revoke",
                client_id=self.client_id
            )
        new_secret = secret.generate_client_secret()
        secret_hash = secret.hash_client_secret(
            secret=new_secret,
            key=env.SECRET_KEY
        )
        client_storage.update_by_id(
            self.client_id,
            {"secret_hash": secret_hash}
        )
        return new_secret

    def update(self, **updates: typing.Any) -> None:
        """Update the client record.

        Args:
            **updates: Fields to update (name, description)
        """
        model.Client.validate_update(updates)
        client_storage.update_by_id(self.client_id, updates)


class ClientAccessResource:
    """Represents the client access resource in Campus API Schema."""

    def __init__(self, parent: "ClientResource"):
        self._parent = parent

    def check(
            self,
            vault_label: str,
            permission: int
    ) -> bool:
        """Check if client has required permission for vault label.

        Args:
            client_id: The authenticated client ID
            vault_label: The vault label to check access for
            required_permission: The permission bitflag required (READ,
            CREATE, UPDATE, DELETE)

        Raises:
            VaultAccessDeniedError: If client lacks the required permission
        """
        client = self._parent.get()
        vault_access = client.permissions.get(vault_label, 0)
        return bool(vault_access & permission)

    def get(
            self,
            vault_label: str
    ) -> int:
        """Get the client's permission bitflag for a vault label.

        Args:
            vault_label: The vault label to get access for

        Returns:
            The permission bitflag for the vault label
        """
        client = self._parent.get()
        return client.permissions.get(vault_label, 0)

    def grant(
            self,
            vault_label: str,
            permission: int
    ) -> None:
        """Grant the client access permission for a vault label.

        Args:
            vault_label: The vault label to grant access for
            permission: The permission bitflag to grant
        """
        client_id = self._parent.client_id
        records = access_storage.get_matching({
            "client_id": client_id,
            "label": vault_label,
        })
        if records:
            current_access = records[0]["access"]
            new_access = current_access | permission
            access_storage.update_by_id(
                records[0]["id"],
                {"access": new_access}
            )
        else:
            access_storage.insert_one({
                "id": uid.generate_category_uid("vault_access"),
                "created_at": schema.DateTime.utcnow(),
                "client_id": client_id,
                "label": vault_label,
                "access": permission,
            })

    def list(self) -> dict[str, int]:
        """List all vault access permissions for the client.

        Returns:
            Dictionary mapping vault labels to permission bitflags
        """
        client_id = self._parent.client_id
        access_records = access_storage.get_matching(
            {"client_id": client_id}
        )
        permissions: dict[str, int] = {}
        for record in access_records:
            label = record["label"]
            access_flag = record["access"]
            permissions[label] = access_flag
        return permissions

    def revoke(
            self,
            vault_label: str,
            permission: int
    ) -> None:
        """Revoke the client access permission for a vault label.

        Args:
            vault_label: The vault label to revoke access for
            permission: The permission bitflag to revoke
        """
        client_id = self._parent.client_id
        records = access_storage.get_matching({
            "client_id": client_id,
            "label": vault_label,
        })
        if not records:
            return
        current_access = records[0]["access"]
        new_access = current_access & ~permission
        if new_access == 0:
            access_storage.delete_by_id(records[0]["id"])
        else:
            access_storage.update_by_id(
                records[0]["id"],
                {"access": new_access}
            )

    def update(
            self,
            vault_label: str,
            permission: int
    ) -> None:
        """Update (replace) the client access permission for a vault label.

        Args:
            vault_label: The vault label to update access for
            permission: The permission bitflag to set (replaces existing)
        """
        client_id = self._parent.client_id
        records = access_storage.get_matching({
            "client_id": client_id,
            "label": vault_label,
        })
        if permission == 0:
            # If permission is 0, delete the access record if it exists
            if records:
                access_storage.delete_by_id(records[0]["id"])
        elif records:
            # Update existing record with new permission
            access_storage.update_by_id(
                records[0]["id"],
                {"access": permission}
            )
        else:
            # Create new record with the permission
            access_storage.insert_one({
                "id": uid.generate_category_uid("vault_access"),
                "created_at": schema.DateTime.utcnow(),
                "client_id": client_id,
                "label": vault_label,
                "access": permission,
            })
