name: Integration Tests

on:
  pull_request:
    branches: [main, staging, weekly]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENV: testing
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          # Configure Poetry to use system Python (not its own bundled version)
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
      - name: Install Campus Suite (full deployment mode)
        run: poetry install --no-root --extras full
      - name: Run Integration Tests
        run: poetry run python run_tests.py
